### ISSUE TITLE
Claves en el locale están mal

### ISSUE THREAD

**Issue by Elolawyn** [rjurado01/rails_jwt_auth#16]
Error: 

```yaml
en:
  rails_jwt_auth:
    mailer:
      confirmation_instructions:
        subject: "Confirmation instructions"
      reset_password_instructions.subject: <------------------------------
        subject: "Reset password instructions"
    errors:
      unconfirmed: "unconfirmed email"
      already_confirmed: "was already confirmed, please try signing in"
      create_session: "invalid %{field} / password"
      expired: "has expired, please request a new one"
      invalid: "invalid"
      blank: "blank"
      not_found: "not found"
      email:
        invlid: "is not an email" <------------------------------
      current_password:
        blank: "blank"
        invalid: "invalid"
      password:
blank: "blank"
```
